indent = 4
margin = 80
remove_extra_newlines = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
format_markdown = true
whitespace_ops_in_indices = true
